Repository divolte/divolte-collector, pull requests merged in 2018-08, with the labels that each got.

#225 Support mapping of hashed values
  docs/mapping_reference.rst
  src/main/groovy/io/divolte/groovyscript/MappingBase.groovy
  src/main/java/io/divolte/server/recordmapping/BytesValueProducer.java
  src/main/java/io/divolte/server/recordmapping/Digester.java
  src/main/java/io/divolte/server/recordmapping/DslRecordMapping.java
  src/test/java/io/divolte/server/DslRecordMapperTest.java
  src/test/java/io/divolte/server/ServerTestUtils.java
  src/test/java/io/divolte/server/recordmapping/BytesValueProducerTest.java
  src/test/resources/TestRecord.avsc
  src/test/resources/digest-bytebuffer.groovy
  src/test/resources/digest-chaining.groovy
  src/test/resources/digest-json.groovy
  src/test/resources/digest-missing-value.groovy
  src/test/resources/digest-string-literal.groovy
  src/test/resources/digest-string-provider.groovy
  src/test/resources/digest-with-documented-algorithms.groovy
  src/test/resources/digest-with-seed.groovy
  src/test/resources/digest-with-string-conversion.groovy
Labels: feature

#214 Use event arrival time as the timestamp for Kafka records
  src/main/java/io/divolte/server/AvroRecordBuffer.java
  src/main/java/io/divolte/server/Mapping.java
  src/main/java/io/divolte/server/topicsinks/kafka/KafkaFlusher.java
  src/test/java/io/divolte/server/filesinks/FileFlusherTest.java
  src/test/java/io/divolte/server/filesinks/hdfs/FileFlusherLocalHdfsTest.java
  src/test/java/io/divolte/server/topicsinks/kafka/ConfluentAvroRecordBufferSerializerTest.java
  src/test/java/io/divolte/server/topicsinks/pubsub/GoogleCloudPubSubFlusherTest.java
Labels: enhancement

#217 Add the LICENSE file to the repository
  LICENSE
Labels: documentation
